### PR TITLE
Add security policy

### PR DESCRIPTION
**Pull request by t8m**
Added security policy. This just converts the existing policy into the MarkDown format.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
I'm assuming that the policy will be updated later.

Adding some links to the glossary would be prudent.  Doesn't have to be here.

**Review by mattcaswell — APPROVED** [review]
I wonder if this can go through under the minor edits policy (once that is approved) - since this is an existing approved policy that is not changing its meaning and is simply being reformatted for the new repo.

**Comment by mattcaswell** [comment]
OMC decided they did not want to wait for the minor edits policy. Therefore I am calling this to a vote now.

````
Topic: Accept the security policy as of 53b2fdfc640960da03ab9519e27de6c0fefe7dd6
Proposed by: Matt Caswell
Issue link: https://github.com/openssl/general-policies/pull/18
Public: yes
Opened: 2022-05-04
Closed: YYYY-MM-DD
Accepted:  yes/no  (for: X, against: Y, abstained: Z, not voted: W)

  Kurt       [  ]
  Mark       [  ]
  Matt       [+1]
  Pauli      [  ]
  Richard    [  ]
  Tim        [  ]
````

**Comment by paulidale** [comment]
Vote: [+1]

**Comment by levitte** [comment]
[+1]

**Comment by kroeckx** [comment]
Voting +1

**Comment by t-j-h** [comment]
Vote [+1]

**Comment by mattcaswell** [comment]
This vote passed and this PR has been merged:

````
Topic: Accept the security policy as of 53b2fdfc640960da03ab9519e27de6c0fefe7dd6
Proposed by: Matt Caswell
Issue link: https://github.com/openssl/general-policies/pull/18
Public: yes
Opened: 2022-05-04
Closed: 2022-05-11
Accepted:  yes  (for: 6, against: 0, abstained: 0, not voted: 0)

  Kurt       [+1]
  Mark       [+1]
  Matt       [+1]
  Pauli      [+1]
  Richard    [+1]
  Tim        [+1]
````

**Pull request closed without merging**
