### PR TITLE
Vote about FIPS rebranding periodicity for premium support customers

### PR DESCRIPTION
**Pull request by paulidale**
Currently just a draft of possible vote text.

The comments are explanatory and will need to be formalised into a process after the vote.

### CODE REVIEW

**Comment by paulidale** [comment]
I couldn't come up with a wording either :)
I can add a comment to the effect: once per contract year with an example.

**Comment by paulidale** [comment]
Any further comments before the vote is called?

**Comment by iamamoose** [comment]
lgtm

**Comment by mattcaswell** [comment]
Seems fine to me

**Comment by paulidale** [comment]
Calling vote based on commit ID 62939851d63594f6ec1fcabce25498abd5b968f2

**Comment by paulidale** [comment]
[+1]

**Comment by t-j-h** [comment]
Vote [+1]

**Comment by iamamoose** [comment]
[+1]

**Comment by mattcaswell** [comment]
Vote: [+1]

**Comment by levitte** [comment]
Er...........  was this vote file supposed to be merged anywhere?  It looks like that wasn't done...

**Comment by paulidale** [comment]
It shouldn't have been closed.  DOn't know why the script did that.

**Comment by paulidale** [comment]
Vote closed and passing.

**Comment by kroeckx** [comment]
Voting 0

**Pull request closed without merging**
