### PR TITLE
Add vote announcement to voting procedure

### PR DESCRIPTION
**Pull request by t8m**
Simple adjustment of the voting procedure to announce votes via openssl-project ML.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
Vote to accept this as of 395652cfdd54343c2d66a009c8b469cfd6b01446

**Comment by paulidale** [comment]
Vote: [+1]

**Comment by iamamoose** [comment]
+1

**Comment by kroeckx** [comment]
voting +1

**Comment by t-j-h** [comment]
Vote: [-1]

**Comment by levitte** [comment]
Vote: [+1]

**Comment by mattcaswell** [comment]
Vote: [+1]

**Comment by paulidale** [comment]
Closing the vote, the vote passes 5 for and 1 against.

**Pull request closed without merging**
