### PR TITLE
Added Run Schedule Table to policy-supplemental directory

### PR DESCRIPTION
**Pull request by TamaraDale**
Updated contractors invoicing policy to link to table & udpated file naming convention to current.

### CODE REVIEW

**Comment by TamaraDale** [comment]
> So this supersedes #28, am I getting that right?

Yes these documents are the latest ones.

**Comment by paulidale** [comment]
Vote: Accept the contractor invoicing policy as of 6a31c748f65a39be1594bf93bd1209880fac8ee1

**Comment by paulidale** [comment]
[+1]

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Vote: [+1]

**Comment by t-j-h** [comment]
Vote: [+1]

Noting that the description of the organisation having no office and only having paid contractors does not belong here at all.
The organisation has resources which aren't paid.

**Comment by TamaraDale** [comment]
Hi Tim,

I think it's been written that way as the invoicing policy only applies 
to the paid resources, but agree we can look at the wording to more 
accurately reflect that as a future change.  I'm sure it wasn't intended 
to mean that paid resources are all we have.

Thanks
Tam

**Comment by paulidale** [comment]
Vote passes.

**Pull request closed without merging**
