### PR TITLE
Update the security policy to include MODERATE issues in prenotifications

### PR DESCRIPTION
**Pull request by iamamoose**

### CODE REVIEW

**Comment by iamamoose** [comment]
vote to accept this as https://github.com/openssl/general-policies/pull/20/commits/0c4587583bc4ca54e1796e8565aadd8a3a551d9b

**Comment by iamamoose** [comment]
vote: [+1]

**Comment by paulidale** [comment]
Vote: [+1]

**Comment by mattcaswell** [comment]
A vote on this is premature. It's not been open for 2 weeks as per the policy change process.

**Comment by iamamoose** [comment]
> A vote on this is premature. It's not been open for 2 weeks as per the policy change process.

good point. will make it ready to vote in 2 weeks.

**Comment by paulidale** [comment]
I don't think the policy prevents opening the vote early, it just says the PR must be open for two weeks and the ready to vote label is applied after this.  It doesn't specify anything about the timing of the vote, just that one must occur.

**Comment by t-j-h** [comment]
> I don't think the policy prevents opening the vote early

I disagree - we don't call for a vote until the two weeks is up - so there is no concept of voting early as such as there isn't a vote until that point. We can always provide indications - but votes have to come after the call for the vote after the two week period has happened.

We need to be consistent on this as the purpose behind the two week period is to enable wider feedback and discussion in case the policy should be altered before getting to a point where we think we have reached a "stable" version good to get a formal vote to make the decision.

**Comment by paulidale** [comment]
Why did this get closed automatically???

I've restored the branch and reopened.

**Comment by mattcaswell** [comment]
> Why did this get closed automatically???
> 
> I've restored the branch and reopened.

The branch has been created in the wrong place, i.e. it has been created directly in the github mirror of the main repo instead of in a personal github fork of the repo. When anyone does a push to the main repo, there is a mirror push to the github copy of the repo. The mirror push will delete any local branches not present in the main repo - and hence this PR will get closed.

This will keep happening every time anyone pushes something to the main repo. @iamamoose - please can you re-create this PR based on a branch in your local fork?

**Comment by iamamoose** [comment]
replaced by: https://github.com/openssl/general-policies/pull/21

**Pull request closed without merging**
